spring:
  # to serialization date or datetime to timestamps in json
  jackson:
    serialization:
      write-dates-as-timestamps: true
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/assignment
    username: postgres
    password: docker

  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      naming:
        naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        ddl-auto: none  #Newer change this config
        dialect: org.hibernate.dialect.MySQLDialect

# Enable logging for config troubleshooting
logging:
  path: /tmp/log
  file:
    name: assignment
    max-size: 10MB
    max-history: 30
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework: INFO


springdoc:
  swagger-ui:
    operationsSorter: method